[book]
title = "Design and Analysis of Algorithms"
authors = ["Suvabrata Chowdhury"]
language = "en"

[output.html]
git-repository-url = "https://github.com/SuvabrataChowdhury/Design_Analysis_of_Algorithms_Notes.git"
